route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'kyro-backend-webhook'

receivers:
  - name: 'kyro-backend-webhook'
    webhook_configs:
      - url: 'http://kyro-backend:8000/incident'
        send_resolved: false
